FRAME_RATE = 60

STARTING_LEVEL = 1

N_PLAYABLE_CHARACTERS = 5

PIXEL_SCALE = 3

WINDOW_W = 1024
WINDOW_H = 720

-- Margins
MARGIN_L = 16
MARGIN_R = 16
MARGIN_T = 8
MARGIN_B = 8

-- Game region dimensions (accounting for margins)
GAME_WIDTH = (WINDOW_W / 2) - MARGIN_L - MARGIN_R
GAME_HEIGHT = WINDOW_H - MARGIN_T - MARGIN_B

-- Player physics constants
ACCEL_X = 32
ACCEL_Y = 32
STANDARD_SPEED = 2

-- Player damage/shield constants
DAMAGE_ITIME = 1.0
SHIELD_RESTORE_TIME = 5.0
SHIELD_RADIUS = 16
SHIELD_LOSE_ANIM_TIME = 0.3

-- Player explosion constants
EXPLOSION_SPEED = 50
EXPLOSION_CIRCLE_COUNT = 10
EXPLOSION_RADIUS_BASE = 5
EXPLOSION_RADIUS_AMPLITUDE = 2